service: python-s3-thumbnail


provider:
  name: aws
  runtime: python2.7
  region: us-east-1
  profile: serverless-admin
  timeout: 10
  memorySize: 128
  iamRoleStatements:
    - Effect: "Allow"
      Action: 
        - "s3:*"
      Resource: "*"
  environment:
    THUMBNAIL_SIZE: "128"


custom:
  bucket: pradeep-gandla-s3-bucket
  pythonRequirements:
    dockerizePip: true

functions:
  s3_thumbnail_gen:
    handler: handler.s3_thumbnail_gen
    events:
       - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .png

plugins:
  - serverless-python-requirements
